# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Varun Kumar Viswanath
full_name: Varun Kumar Viswanath
email: vkviswan@ucsd.edu
email2: varunknath@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zuko09.github.io/" # the base hostname & protocol for your site
github_username:  zuko09
twitter_username: varunknath
linkedin_username: varun-viswanath-aab70345
stackoverflow: 4749362/zuko09
include: ['_pages']
footer-links-active:
  stackoverflow: true

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-redirect-from
